--liquibase formatted sql

--changeset Olga Kargan:create-faculty

create table faculties
(
    id         bigint generated by default as identity
               primary key,
    color      varchar(1024),
    name       varchar(1024)
);

alter table faculties
    owner to student;